### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chick0** [chick0/slow_postbox#1]
# 로그인
- [x] 이메일 & 비밀번호

# 회원가입
- [x] 약관 동의
- [x] 이메일 인증
- [x] 비밀번호 입력
- [x] 가입 오류 핸들링 / 중복 가입시 발생하는 유니크 키 문제

# 비밀번호 분실
- [x] #15

# 이메일 인증 개선
- [x] 이메일 주소 같이 저장
- [x] 이메일 인증 중복 불가능 하도록 수정

# 편지 작성
- [x] 작성 & 저장
- [x] 삭제
- [x] 개수 제한
- [x] CSRF 적용
- [x] #12 , #17
- [x] #16 

# 편지 읽기
- [x] 이메일에 편지를 읽을 수 있는 링크를 전송
- [x] 링크로 들어오면 로그인을 해야함
